name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Well done for submitting your first issue! A moderator will see you soon.'
        pr-message: "Well done for submitting yout first Pull Request! I'll review your idea as soon as I'm online."
